### ISSUE TITLE
Create text inputs

### ISSUE THREAD

**Issue by payton-burr** [bryce-senninger/Project_1#5]
## Task

- [x] Create a text input for job search e.g. Software Developer, Web Developer, etc...

- [x] Create a text input for job location

**Comment by payton-burr** [comment]
## Task
- [x] Create a text input for what job to search for e.g. Software Developer, Web Developer, etc...

- [x] Create a text input for location
