### ISSUE TITLE
Create Job Listing Page

### ISSUE THREAD

**Issue by payton-burr** [bryce-senninger/Project_1#7]
## Task

- [x] Take homepage (index.html) and change it to include a table

- [x] Make sure site is linked site to homepage (index)

- [x] Create an AJAX call that pulls the API
